Fix `_OgreCommonExport_.converter` not initialized on Blender 4.4. Blender 4.4 release notes say nothing about addon API change, but I am experiencing ``` Traceback (most recent call last):   File "/home/richardn/.config/blender/4.4/scripts/addons/io_ogre/ui/export.py", line 78, in draw     if self.converter == "unknown":        ^^^^^^^^^^^^^^   File "/usr/share/blender/4.4/scripts/modules/bpy_types.py", line 940, in __getattribute__     return super().__getattribute__(attr)            ~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^ AttributeError: 'OP_ogre_export' object has no attribute 'converter' ``` after upgrading to 4.4 (Error triggered when opening the export dialog, and due to the error no export settings widget will be shown, and export will fail dramatically). After some investigation I am still confused why old code broke (instantiation should have happened before `.draw()` is called?), but what I changed here respects what is written in Blender API docs, and fixes the problem I bumped into.